cloudfoundry/bosh-backup-and-restore

ci/pipelines/bbr/pipeline.yml
- This fixes the "get" step erroring with:
null health check failed. <https://null/health_check/custom.json> Resource unavailable.
Signed-off-by: Neil Hickey <nhickey@vmware.com>
=> Add hostname param to pool resource

ci/pipelines/docker-build/pipeline.yml
- This container image pulls the latest of each dependency on trigger,
this timer is a cheap way to get depedencies up to date instead of
trigger on their relevant repos / release artifacts
- This also includes a rename of master -> main for the repo branch
https://github.com/pivotal-cf/cryogenics-docs/issues/81
Signed-off-by: Neil Hickey <nhickey@vmware.com>
=> Trigger bbr-pcf-pipeline-tasks build every week

ci/tasks/prepare-artefacts-for-pivnet/release.yml.erb
- Remove OpsManager and TAS as "dependencies". They were never real
dependencies, they're just things that bbr can work with.
- Add advice to the product description. Always use the latest
CLI. Always take backups before and after upgrading.
=> Update tanzunet release info and advice

ci/pipelines/bbr/pipeline.yml
Many repos have moved from cloudfoundry-incubator org to cloudfoundry.
=> [ci] update CI following GH org refactoring

instance/deployed_instance_test.go, instance/job.go, instance/job_finder.go, instance/job_finder_test.go, instance/job_test.go, ssh/fakes/fake_logger.go, ssh/fakes/fake_opts_generator.go, ssh/fakes/fake_remote_runner.go, ssh/fakes/fake_remote_runner_factory.go, ssh/fakes/fake_ssh_connection.go, ssh/fakes/fake_ssh_session.go, ssh/remote_runner.go, ssh/remote_runner_test.go
This PR depends on #431 and replaces #426 .
We have heard reports that if a backup or restore script prints out huge amounts of data to stdout, this can cause the BBR CLI to crash.
The reason this happens seems to be that a method in the CLI was effectively buffering all the data from the script's stdout. This PR changes that method so that it streams stdout to an io.Writer, instead of caching and returning it.
Changes to files in the `fakes` directory can be ignored, since they are auto-generated. Each commit keeps all the tests green, and is individually motivated in the commit message.
=> Make BBR more robust to large stdout streams.

bosh/client.go, bosh/client_test.go
[#182248334]
Newer versions of the Stemcells don't list `ssh-rsa` algorithm
as an option while performing the handshake process.
This change remains backward compatible while also allowing
handshake to succeed by listing other accepted algorithms.
SSH implementation will transparently choose one that works
taking into account:
- Order in which algorithms were specified
- Algorithms supported by both client and server
- Specified Host and public key format
- Additional ClientConfig settings
=> Fix ssh issues with Windows Stemcells 2019.46+

go.mod, go.sum
After the `bosh-cli` update, we had a bunch of unnecessary stuff in
`go.mod` and `go.sum`. This PR tidies it up by running `go mod tidy`
=> Tidy up go.mod and go.sum

ci/pipelines/bbr/pipeline.yml, ci/tasks/bbr-s3-config-validator-validate-aws-s3-config/task.sh
We're seeing some CI runs like this[1] which ought to fail, but don't. This is because CI is currently only tracking whether or not our secrets redactor succeeds, not whether the underlying command succeeds.
We can fix this by using `set -o pipefail` at the top of the bash script.
[1] https://ci.cryo.cf-app.com/teams/bosh-backup-restore/pipelines/bbr-cli/jobs/test-build-s3-config-validator/builds/841
=> Fix evergreen s3-validator pipeline

ci/pipelines/bbr/pipeline.yml
- We are now automatically releasing every month to be in line with what we do with other products on the team
- Also removed the deprecated gitgat Concourse resource
- Removed the All CI group (as we can just press Shift and select all the groups to have the same behaviour)
- Stop creating stories for OSL (this is been dealt with in another pipeline)
- Updated the Slack message to be make actions explicit
=> [ci] Release every month

s3-config-validator/src/cmd/main.go, s3-config-validator/src/internal/config/config.go, s3-config-validator/src/internal/config/config_test.go, s3-config-validator/src/internal/configPrinter/configPrinter_test.go, s3-config-validator/src/internal/runner/export_test.go, s3-config-validator/src/internal/runner/runner.go, s3-config-validator/src/internal/runner/runner_test.go, s3-config-validator/src/internal/s3/export_test.go, s3-config-validator/src/internal/s3/s3client.go, s3-config-validator/src/internal/s3/s3client_test.go
In the validator, when IAM profile is set in the configuration:
- validate presence of backup buckets for un-versioned buckets
- clarify error messages
- in order to avoid confusion, prevent the following values from being set:
- AWS credentials
- endpoint
[#184963912]
=> fix: Make validator work with instance profiles

ci/tasks/bbr-s3-config-validator-validate-aws-s3-config/task.yml, ci/tasks/bbr-system-deployment/task.yml, ci/tasks/bbr-upload-system-test-releases/task.yml
The CI is breaking because it references a cryo-essentials-cf6 image, which has now been deleted.
Changed to reference the latest cryo-essentials image
=> Changed to use cryo-essentials - the cf6 version has gone

ci/images/backup-and-restore-minimal/Dockerfile
We need the latest BOSH CLI to support IAM assumed role
=> backup-and-restore-docker-image use latest BOSH CLI

bosh/build_client_test.go, go.mod, go.sum, integration/deployment/backup_cleanup_test.go, integration/deployment/backup_test.go, integration/deployment/cli_test.go, integration/deployment/pre_backup_check_test.go, integration/deployment/restore_cleanup_test.go, integration/deployment/restore_test.go, integration/deployment/web_mock_helpers.go, integration/director/cli_test.go, internal/cf-webmock/README.md, internal/cf-webmock/mockbosh/delete_deployment.go, internal/cf-webmock/mockbosh/deploy.go, internal/cf-webmock/mockbosh/errand.go, internal/cf-webmock/mockbosh/get_deployments.go, internal/cf-webmock/mockbosh/info.go, internal/cf-webmock/mockbosh/manifest.go, internal/cf-webmock/mockbosh/mockbosh.go, internal/cf-webmock/mockbosh/ssh.go, internal/cf-webmock/mockbosh/task.go, internal/cf-webmock/mockbosh/task_output.go, internal/cf-webmock/mockbosh/tasks.go, internal/cf-webmock/mockbosh/vms.go, internal/cf-webmock/mockhttp/http_mock.go, internal/cf-webmock/mockhttp/server.go, internal/cf-webmock/mockuaa/mockuaa.go
cf-webmock from https://github.com/pivotal-cf-experimental/cf-webmock is no longer maintained, and the repo has been archived. It has therefore been incorporated into this repo, so that we can keep it up to date (updating to Ginkgo V2 being the thing we want to do next). There are no licensing concerns as both this project and cf-webmocks have Apache 2.0 licenses and were largely contributed by VMware.
=> chore: incorporate cf-webmock in this repo

ci/pipelines/bbr-cli/pipeline.yml
It will run daily or on every commit as an experiment. One day it may make sense to run it on every PR too, but let's start with something that can't block the pipeline.
=> chore: add govulncheck to pipeline

ci/tasks/bbr-build/task.sh
[#185311814]
the filename wasn't updated when copy and pasting. This should fix it.
=> fix bad filename

ci/tasks/bbr-update-homebrew-formula/task.sh
Make it possible to install the BBR CLI on a MacOS device powered by Apple's M1 via Homebrew.
[#186079257]
=> Make sure BBR can be installed in M1 devices

ci/images/backup-and-restore-minimal/Dockerfile, ci/images/backup-and-restore/Dockerfile
- update minimal to be jammy based
- update backup-and-restore to not use rbenv from `sstephenson` but rather the real repos (it's forwarding now, but who knows what it will do in the future
- update apt packages to include the libraries specified in ruby-build docs
=> modernize images

ci/images/backup-and-restore/Dockerfile
the build for the image currently fails because of two issues
- gcloud sdk version in dockerfile is too old to work on python 3
- git crypt won't build against ossl3 unless compatibility flags are provided
=> fix build: update gcloud, ossl3 compatibility gi-crypt

ci/pipelines/bbr-cli/pipeline.yml
[#187071309]
they currently force push. That created issues when the same job got triggered twice ( for unknown reasons ) and job n-1 "overtook" job n ( n used a newer HEAD ) and force pushed over the changes made by n.
=> all bumpers should be serial

s3-config-validator/.gitignore, s3-config-validator/src/test/binary/binary_test.go
only ignore the top level `build` folder
=> Bump timeouts

ci/tasks/bbr-s3-config-validator-unit-test/task.sh
It’s generally a good practice to add a call to go mod tidy before running go mod vendor. This ensures that your go.mod file is up-to-date and accurately reflects the dependencies before running the tests.
Not calling go mod tidy caused an issue in one of the dependencies updates because go version needed to be changed to 1.23 from 1.22
=> add a go mod tidy before go mod vendor

.github/workflows/run-test-pyramid.yml
there are multiple go mod files in this porject and since one of them at least was updated to 1.23, the go action should run with 1.23
=> update the go version used by the github action
